name: CI

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  unit-tests-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache-dependency-path: ./bugtracker-backend/go.sum

      - name: Install go-junit-report
        run: |
          go install github.com/jstemmer/go-junit-report@latest

      - name: Execute Backend Unit tests
        working-directory: ./bugtracker-backend
        run: |

          go test -json -coverprofile=coverage.out -covermode=atomic ./...
          go tool cover -func=coverage.out > coverage.txt

          echo "## Go Test Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat coverage.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

          go test -v ./... 2>&1 | go-junit-report > test-results.xml

      - name: Publish backend test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Backend Unit Test Report
          path: ./bugtracker-backend/test-results.xml
          reporter: jest-junit

  unit-tests-frontend:
    needs: unit-tests-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache-dependency-path: ./bugtracker-frontend/package-lock.json

      - name: Execute Frontend Unit tests
        working-directory: ./bugtracker-frontend
        run: |
          npm ci
          npm test | tee full_output.txt
 
          echo "## Frontend Test Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat full_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Publish frontend test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Frontend Unit Test Report
          path: ./bugtracker-frontend/test-results.xml
          reporter: jest-junit

  api-tests:
    needs: [unit-tests-backend, unit-tests-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Launch Application Services
        run: |
          docker compose up -d --build
          npx wait-port http://localhost:8080/api/health -t 30000

      - name: Execute API tests
        working-directory: ./tests-api
        run: |
          npm ci
          npm playwright test

      - name: Shut down Application Services
        run: |
          docker compose down

      - name: Upload API test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: API Test Results
          path: ./tests-api/test-results/
          retention-days: 7

      - name: Upload API Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: API Test Playwright Report
          path: ./tests-api/playwright-report/
          retention-days: 7

      - name: Publish API test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: API Test Report
          path: ./tests-api/test-results/results.xml
          reporter: jest-junit    